### PR TITLE
FIX Reports linking to pages now use the correct CMS edit link

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes https://github.com/dnadesign/silverstripe-elemental/issues/629

### CODE REVIEW

**Comment by robbieaverill** [comment]
Maybe we should just sent both of those links straight to the page, since inline editing is likely to become the default behaviour going forward

**Comment by robbieaverill** [comment]
Alright I've just updated it so it works

**Comment by robbieaverill** [comment]
Technically it’s a breaking change, but I’m ok with it

**Comment by ScopeyNZ** [comment]
`getEditLink()` probably should be `@internal` anyway 😉

**Pull request merged**
