### PR TITLE
Pulls/4.0/layout annoIEnces

### PR DESCRIPTION
**Pull request by NightJar**
fix layout issues in IE & Edge

### CODE REVIEW

**Comment by robbieaverill** [comment]
Changes LGTM but I'd like to test this in other browsers before merging

**Comment by NightJar** [comment]
Tests were run in chrome, safari, ie11, edge... and I think firefox (but not by me - @raissanorth I think you did though right?)

**Comment by NightJar** [comment]
Here is a picture of:
```
Edge | Chrome
---------------
IE11 | Firefox
```

image

Previously the plus icon was below the bar on edge, and the line was higher than the edges of two elements, and overlays the top one (and the plus icon is a bit out):

image

**Comment by ScopeyNZ** [comment]
Seems like you guys have the bases covered...

**Pull request merged**
