### PR TITLE
Add PHP 7.2 and various SilverStripe recipe versions to Travis matrix

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Some issues with SS 4.2 highlighted in the test failures here, related to versioned. cc @tractorcow if you're interested.

**Comment by NightJar** [comment]
Will wait to merge.

**Comment by tractorcow** [comment]
It looks like 4.2 versioned picked up a big in your elemental test. Are you doing a set_stage('') somewhere?

**Comment by tractorcow** [comment]
It's this code.

```
$page = Versioned::get_by_stage($class, Versioned::get_stage())->filter($areaID, $this->ID);
```

Not checking to see if get_stage() is null or not.

**Comment by tractorcow** [comment]
I've raised https://github.com/silverstripe/silverstripe-versioned/pull/142 as an improvement to the current error checking.

**Comment by robbieaverill** [comment]
Updated

**Pull request merged**
