### PR TITLE
FIX Removing loading indicators by introducing optimistic deletes

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Partially addresses #485 - ensuring loading indicators don't appear for the whole elemental area. In the case of an error (such as 403) it will re-show the block.

### CODE REVIEW

**Comment by emteknetnz** [comment]
@ScopeyNZ This pull request hasn't had any activity for a while.  Looks like travis is red.  Also it's on a pretty old version of elemental so possibly consider rebase/retarget to 4.4. Are you going to be doing further work on this PR, or would you prefer to close this PR now?

**Comment by robbieaverill** [comment]
It's a real shame we let things like this go stale 😞

**Comment by emteknetnz** [comment]
It seems like there's going to be no further activity on this pull request, so we've closed it for now. Please open a new pull-request if you want to re-approach this work, or for anything else you think could be fixed or improved.

**Comment by michalkleiner** [comment]
> It's a real shame we let things like this go stale 😞

Totally agree!

**Pull request closed without merging**
