### PR TITLE
Created a Croatian translations

### PR DESCRIPTION
**Pull request by hdpero**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hey @hdpero - thanks for contributing! Our translations (non English) are managed via Transifex and are pulled in periodically and these language files updated automatically.

I've created a Croatian (hr) language in the Transifex project. Would you mind entering your translations there instead? Thanks!

https://www.transifex.com/silverstripe/silverstripe-elemental/language/hr/

**Comment by robbieaverill** [comment]
FYI I've just pushed an updated master file (English) which has a few new strings that were added recently.

**Comment by hdpero** [comment]
Hi @robbieaverill I cannot "Join Team" and access Croatian language on Transifex. Could you please add me?

**Comment by robbieaverill** [comment]
@hdpero I've accepted your join request - thanks :)

**Pull request closed without merging**
