### PR TITLE
FIX allow extensions to modify canXYZ methods

### LINKED ISSUE #29: BaseElement's canXYZ() methods can't be extended
They need to call the parent's methods before defining their own logic, otherwise the extension hook is not exposed.

### PR DESCRIPTION
**Pull request by robbieaverill**
* Resolves #29

### CODE REVIEW

**Comment by wilr** [comment]
This fix will call the extensions but it won't actually modify the response to it right? Think the pattern for this should be something like

**Comment by robbieaverill** [comment]
@wilr yeah, it will call the parent method but won't use its results. It's `DataObject::canDelete()` for example that provides the extension hook.

**Comment by wilr** [comment]
See https://github.com/silverstripe-australia/silverstripe-advancedworkflow/blob/master/code/dataobjects/WorkflowInstance.php#L412-L416

**Comment by robbieaverill** [comment]
@wilr no worries, let's go that way!

**Comment by robbieaverill** [comment]
FYI I've gone with PSR-2 since it's coming - if you want me to use standard SS style I'm happy to change it

**Comment by wilr** [comment]
Nah PSR1/2 FTW

**Comment by robbieaverill** [comment]
Cool. Hold this PR - I'm not sure it's working correctly with `canView()`.

**Comment by robbieaverill** [comment]
Looks like versioned-data-objects is returning `0` somewhere in the `canView` permissions check and preventing them from being visible. Looking into it.

**Comment by robbieaverill** [comment]
@wilr - having had a quick read [of the `Versioned` docs about permissions](https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/02_Developer_Guides/00_Model/10_Versioning.md#permissions) it sounds sensible to me that this module should implement its own permission check for `canView` which it does already, so perhaps we shouldn't try to allow the extension hook for it?

I'm confused about two things here:

1. Is [silverstripe-versioned-dataobjects](https://github.com/heyday/silverstripe-versioneddataobjects) required over the framework's included `Versioned` functionality which can apply to `DataObject`s as well?
2. Is there a way to still provide the extension hooks from `BaseElement`, while not letting the permission errors from `Versioned` prevent the actions? I'm by no means a master in this, but would moving the `canXYZ` methods into a `BaseElementExtension` which would extend `VersionedDataObject` be a better option? This way the result you return from the `canXYZ` method would be isolated to that extension, and the base permission check would treat it as an extension's two cents rather than the base `DataObject`s two cents...?

**Comment by robbieaverill** [comment]
Hey @wilr - what do you think about this change?

**Comment by robbieaverill** [comment]
@wilr - rebased onto latest master changes

**Comment by wilr** [comment]
Yeah I think that is possibly a better way to go and allows users to sub in anything else for permissions.

**Pull request merged**
