### PR TITLE
fix form submission, when form block is inside another block

### PR DESCRIPTION
**Pull request by sukhwinder-somar**
Creating new PR, related to the https://github.com/dnadesign/silverstripe-elemental-userforms/pull/78

## Issue
- https://github.com/dnadesign/silverstripe-elemental-userforms/issues/27

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Please change to this instead:

```php
public function handleElement()
{
    $id = $this->owner->getRequest()->param('ID');

    if (!$id) {
        user_error('No element ID supplied', E_USER_ERROR);
        return false;
    }

    /** @var DataObject $elementOwner */
    $elementOwner = $this->owner->data();

    if (!$elementOwner->hasExtension(ElementalAreasExtension::class)) {
        user_error(get_class($elementOwner) . ' doesnt have the ElementalAreasExtension applied', E_USER_ERROR);
        return false;
    }

    $elementalAreaRelations = $elementOwner->getElementalRelations();
    if (!$elementalAreaRelations) {
        user_error(get_class($elementOwner) . ' has no ElementalArea relationships', E_USER_ERROR);
        return false;
    }

    $element = $this->findElement($elementalAreaRelations, $elementOwner, $id);

    if ($element) {
        return $element->getController();
    }

    user_error('Element $id not found for this page', E_USER_ERROR);
    return false;
}

private function findElement(iterable $elementalAreaRelations, DataObject $owner, $id): ?DataObject
{
    foreach ($elementalAreaRelations as $elementalAreaRelation) {
        $elements = $owner->$elementalAreaRelation()->Elements();
        $found = $elements->filter('ID', $id)->First();

        if ($found) {
            return $found;
        }

        /** @var BaseElement $element */
        foreach ($elements as $element)             {
            if (!$element->hasExtension(ElementalAreasExtension::class)) {
                continue;
            }

            /** @var BaseElement&ElementalAreasExtension $element */
            $found = $this->findElement($element->getElementalRelations(), $element, $id);

            if ($found) {
                return $found;
            }
        }
    }

    return null;
}
```

This is similar to your approach, but with the following key differences:
- Adds an additional protection against `$elementOwner` not having the `ElementalAreasExtension` applied (in the case of custom nested elements)
- Checks for use of the `ElementalAreasExtension` instead of the `Elements` method, which allows for the relation to have any arbitrary name instead of just the one that the elemental list module uses
- Flips the logic of `findElement()` somewhat, so we have no `foreach` loop in the `handleElement()` anymore, delegating all of the logic to `findElement()`.
- Adds appropriate type hinting to the new method

I've tested this in conjunction with https://github.com/dnadesign/silverstripe-elemental-userforms/pull/78 and together they resolve the bug, so after you've made these changes I'll be happy to merge them both.

**Comment by sukhwinder-somar** [comment]
sweet, I have updated the code with your changes, but I didn't test it so I'm hoping it will work as you have already tested it....

**Comment by sukhwinder-somar** [comment]
sweet, I have updated the code with your changes, but I didn't tested it so I'm hoping it will work as you have already tested it....

**Comment by GuySartorelli** [comment]
Please test the changes. I will merge once you have confirmed they work on your end.
The whole point of a pull request is that there are at least two people involved.

**Comment by sukhwinder-somar** [comment]
Sure, then I will update you tomorrow or tonight after testing...

**Comment by sukhwinder-somar** [comment]
Hi,

I have tested this and can confirm the above is working for me on First and Second Level of page.

While testing I had first and second level forms on same page and I found out If I was submitting one of them, then both of them was showing confirmation messages, which I feel looks weird, so thought I should tell you....

thanks,

**Comment by GuySartorelli** [comment]
> While testing I had first and second level forms on same page and I found out If I was submitting one of them, then both of them was showing confirmation messages, which I feel looks weird, so thought I should tell you....

That's a known issue, captured in https://github.com/dnadesign/silverstripe-elemental-userforms/issues/50 - it was fixed recently so if you update your dependency it shouldn't happen anymore.

**Review by GuySartorelli — APPROVED** [review]
Looks good to me, thanks for fixing this.

**Comment by GuySartorelli** [comment]
Ahh, sorry, I just realised this is targetting the wrong branch.
Please retarget it to the `4.11` branch. You may need to [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) afterward.

**Comment by sukhwinder-somar** [comment]
All good, thanks for all support 😊 🙏

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Oops, looks like when you reset the commits you accidentally reverted the changes from https://github.com/silverstripe/silverstripe-elemental/pull/1107#pullrequestreview-1672672600 as well!

**Comment by sukhwinder-somar** [comment]
apologies again, I forgot to cherry pick both commits, but have added it now 😅

**Review by GuySartorelli — APPROVED** [review]

**Pull request merged**
