### PR TITLE
API Deprecate GraphQL

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-admin/issues/1799

### CODE REVIEW

**Review by GuySartorelli — COMMENTED** [review]
Does this mean you can't get elemental blocks in a front-end schema anymore without adding a bunch of boilerplate? Or was this all exclusively for the admin schema?

**Comment by emteknetnz** [comment]
Everything be removed was only intended for the admin schema

**Comment by emteknetnz** [comment]
unit test failures should be resolved by https://github.com/silverstripe/silverstripe-versioned/pull/464

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
