### PR TITLE
API Remove reference HistoryControllerFactory.

### PR DESCRIPTION
**Pull request by maxime-rainville**
Fix https://github.com/silverstripe/silverstripe-versioned-admin/issues/67 and https://github.com/silverstripe/silverstripe-cms/issues/2277

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I'm not convinced that we should do this in the 3 branch. The 4 branch will be released soon(-ish) and we can remove it from that line (it has 4.3 as a minimum requirement), but the 3 line can still run with 4.2 that would benefit from this code.

**Comment by robbieaverill** [comment]
It depends on the constraint in this module. 3.x will still work on SS 4.3

**Comment by ScopeyNZ** [comment]
Yeah but people using the latest version of the 3 branch on 4.2 would no longer have the new page history viewer with this patch.

**Comment by maxime-rainville** [comment]
Cool ... I brought back the YML config and tweaked the logic to return `void` instead of `false`. I think we're better off waiting until the versioned-admin PR is merged before merging this one. Removing `HistoryControllerFactoryExtension` from 4 can wait until the 4.3 release is out the door.

**Pull request merged**
