### PR TITLE
Added improvements to rendertemplates

### PR DESCRIPTION
**Pull request by gorriecoe**
Added extend updateRenderTemplates.

Added style based template suffix.

### CODE REVIEW

**Comment by gorriecoe** [comment]
I have taken a different approach to this now.  By splitting the templates into there classes we modify them easier.

**Comment by robbieaverill** [comment]
How do you feel about refactoring this a little to reduce some of the duplication?

**Comment by derralf** [comment]
will this (or at least the extension hook which would be very usefull) be merged/released anytime soon?

**Comment by robbieaverill** [comment]
@derralf we won't be releasing a new major version of this module in the near future, so best to use the `3.0.x-dev` constraint. We could also cherry-pick this back into a 2.x release (minor) but this wouldn't likely happen for a few weeks or months.

**Comment by derralf** [comment]
@robbieaverill maybe a dumb problem/question, but how do I install this with SS4.1?
`3.0.x-dev` requires `silverstripe/versioned-admin 1.x-@dev` which requires `silverstripe/admin 1.2.x-dev`
but `silverstripe/recipe-cms 1.1.0 ` (SS4.1) requires `requires silverstripe/admin 1.1.0@stable` so composer won't install/update to `3.0.x-dev`

**Comment by robbieaverill** [comment]
3.0.x-dev looks like it requires SS 4.2 or higher

**Pull request merged**
