### PR TITLE
Fix not needed duplication when restoring a page from archived state

### PR DESCRIPTION
**Pull request by AljosaB**
Fix for https://github.com/silverstripe/silverstripe-elemental/issues/1093

### CODE REVIEW

**Comment by GuySartorelli** [comment]
The issue describes a perceived issue with the current behaviour and doesn't mention fluent. Your change is to documentation, specifically for the "Elemental with Fluent setup" section....

Can you please describe a bit more how this change to documentation fixes the issue you're linking to?

**Comment by AljosaB** [comment]
The issue does mention fluent, it's literally the second word under the setup section :) Also the provided [link](https://github.com/silverstripe/silverstripe-elemental/blob/5/docs/en/advanced_setup.md#elemental-with-fluent-setup) is pointing to the fluent part of documentation and quoted part of code is from the same section :)

The intention is to improve the suggested code in the documentation when using elemental with fluent. The issue mentioned (I'm the author of both) is not describing a malfunction / bug in elemental's code, but in the documentation's code.

**Comment by GuySartorelli** [comment]
> The issue does mention fluent, it's literally the second word under the setup section

My apologies, I missed that. It's not mentioned after that so I guess I was focusing on the main description, and the issue didn't make it very clear that this was only a documentation problem.

> I'm the author of both

Lol yes, thank you, I can see that.

Please update your commit message to start with the `DOC` prefix as per our [contribution documentation](https://docs.silverstripe.org/en/5/contributing/code/#commit-messages) so that it doesn't trigger an automated patch release.

**Comment by AljosaB** [comment]
Indeed, it wasn't very clear it's only about the docs.

Commit message fixed :+1:

**Review by GuySartorelli — APPROVED** [review]
Seems okay. Thanks for submitting it. I'll merge when it goes green

**Pull request merged**
