### PR TITLE
NEW Replace window.confirm usage with @silverstripe/reactstrap-confirm

### PR DESCRIPTION
**Pull request by ScopeyNZ**
This also extracts the use of entwine/jQuery within our React components to an external "lib" file/class to make it easier to test and hide away some of the ugliness. This can probably be expanded on in the future when features are added that interact with the preview in more detail

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Ah, I forgot about Behat.

**Comment by robbieaverill** [comment]
Let's rebase onto `4`

**Comment by emteknetnz** [comment]
@ScopeyNZ This pull request hasn't had any activity for a while.  Looks like it still needs rebasing and to get travis green. Are you going to be doing further work on it, or would you prefer to close it now?

**Comment by emteknetnz** [comment]
It seems like there's going to be no further activity on this pull request, so we've closed it for now. Please open a new pull-request if you want to re-approach this work, or for anything else you think could be fixed or improved.

**Pull request closed without merging**
