### PR TITLE
Fix infinite loop on write

### PR DESCRIPTION
**Pull request by Lolly101**
Fixes https://github.com/dnadesign/silverstripe-elemental/issues/318

### CODE REVIEW

**Comment by robbieaverill** [comment]
Looks good, tests pass - 👌 

@Lolly101 Do you want this to be released as a patch fix in the 2.x release line? If so I'll retarget this pull request against 2.0.x or 2.1.x, otherwise it's unlikely to receive a new release since we're currently supporting elemental 3.x by default.

**Comment by Lolly101** [comment]
Yes 2.x please because we're not using SilverStripe 4.2 yet

**Comment by robbieaverill** [comment]
Which version are you using? 2.0 or 2.1?

**Comment by Lolly101** [comment]
2.1 thanks :)

**Pull request merged**
