### PR TITLE
Fr translation

### PR DESCRIPTION
**Pull request by DrMartinGonzo**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks for the pull request! We manage our non-English localisations through [Transifex](https://www.transifex.com/silverstripe/silverstripe-elemental/language/fr/) - would you mind submitting them there instead? The non-English files in these projects are automatically updated so changes like this would be undone during the next release process.

**Comment by bummzack** [comment]
@robbieaverill couldn't you push from the `fr.yml` to transifex? Eg. something like:

    tx push -t -l fr

**Comment by robbieaverill** [comment]
True, we can do that!

**Comment by robbieaverill** [comment]
Pushed

**Pull request merged**
