### PR TITLE
ENH Refactor Element to function component

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-elemental/issues/1164

I'm splitting the linked issue into two PRs
- Firstly I'll do this one that only refactors the existing class component to a function component
- Once this is merged, I'll do a second PR to do the GraphQL refactor

Note that I've removed the `getDerivedStateFromError() / childRenderingError` functionality because:
- I didn't find a replacement for it using functional components
- We don't use getDerivedStateFromError() in any other components, so I think for consistency we don't actually want it

### CODE REVIEW

**Comment by GuySartorelli** [comment]
I am reliably getting this error in the developer console whenever I expand an inline-editable block and then click "save" in the page (note: NOT when I click the `...` menu and save the block from there)

> Uncaught (in promise) Invariant Violation: Store reset while query was in flight (not completed in link chain)

Other than that it seems to work as expected locally. Haven't taken a proper look at the code yet but at a glance it looks okay.

**Comment by emteknetnz** [comment]
That's an existing console error unrelated to this PR. It's coming from Apollo.

**Comment by GuySartorelli** [comment]
Please replace `getDerivedStateFromError()` with `componentDidCatch()` as per https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary

I'm not sure exactly what scenarios this is used in, but I have seen the "Something went wrong with this block. Please try saving and refreshing the CMS" error a bunch of times in my time developing with this module and it's always pointed out a problem that needed to be fixed.
Without this, it seems likely there will be silent failures, or failures which are only indicated in the developer console, which previously would have been clearly pointed out in the DOM.

This is just a refactor, not a change of functionality, so where there's a suitable functional component replacement (and in this case there is), we should just use it so that the functionality after the refactor is as close as possible to the functionality before the refactor.

If we decide later we want to remove this, we can remove it at that time - but that's not a decision I think we should be making here.

**Comment by GuySartorelli** [comment]
I had originally requested replacing `getDerivedStateFromError()` but it looks like error boundaries are no longer directly supported in react. While I think losing that functionality isn't desirable, keeping it is probably more effort than it's worth right now.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
