### PR TITLE
Add extension hooks to requireDefaultRecords

### PR DESCRIPTION
**Pull request by StephenMakrogianni**
Added extension hooks to allow external modules to add their own functionality.

### CODE REVIEW

**Comment by michalkleiner** [comment]
Nice addition!

One minor thing — I'd suggest renaming the hooks to `onBeforeRequireDefaultElementalRecords` and similarly `onAfterRequireDefaultElementalRecords` as the current hook names, i.e. method names in the extension class, aren't necessarily super clear where they hook into.

**Comment by robbieaverill** [comment]
Good suggestion @michalkleiner. Would you mind updating @StephenMakrogianni? I'll update your other PR manually once this is merged.

**Comment by StephenMakrogianni** [comment]
Yeah great idea. I'll jump on it now.

**Comment by robbieaverill** [comment]
Subsites compat module PR updated with https://github.com/dnadesign/silverstripe-elemental-subsites/commit/3c5060da0c37f8fcddaa024fd9a0c80825e20a0e

**Pull request merged**
