### PR TITLE
ENH BaseElement::getType() use static::class instead of __CLASS__ for…

### PR DESCRIPTION
**Pull request by christopherdarling**
## Description

Without this then the default is always the singular name of `BaseElement` ('Block'). This allows each subclass to have a more sensible default based on `$singular_name`.

## Issues

- https://github.com/silverstripe/silverstripe-elemental/issues/831

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Hi. Thank you for your contribution.

I notice you removed the pr template from the description - I've added it back in. Please fill in all sections of the template, and tick all the boxes that don't apply.

This will give a clear indicator of the status of the contribution and make it easier for us to review it.

**Comment by christopherdarling** [comment]
@GuySartorelli apologies - updated

**Comment by GuySartorelli** [comment]
Thanks for that. Can you please also find or create an issue and link to it, as per the contribution guide?

**Comment by christopherdarling** [comment]
> Thanks for that. Can you please also find or create an issue and link to it, as per the contribution guide?

Sorry, I thought this sufficed

image

Will add that same link to the description now

**Comment by GuySartorelli** [comment]
Thanks! I hadn't even noticed the mention, which is exactly why there's a spot for it in the pr template hahs

**Review by GuySartorelli — APPROVED** [review]
LGTM.

**Comment by christopherdarling** [comment]
Thanks @GuySartorelli

**Pull request merged**
