### PR TITLE
Add 'Duplicate' action to elements.

### PR DESCRIPTION
**Pull request by JoshuaCarter**
- Duplicates element.
- Adds ' (Copy)' to the Title.
- Reorder duplicate to position after the cloned element.

We're currently on 4.0.5 so I've PR'd this to the 4.0 branch. I tried a quick cherry-pick onto the 4 branch but it didn't work right off the bat and I'm lazy :sleepy: 

Direction/feedback welcome.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Nice! Awesome to see some more contributions to this React stuff. Hopefully you found it actually kind of fun and easy?

This will need to be based on the `4` branch, as it's a minor feature it'll have to go into Elemental 4.4. You should be able to do this with:

```
git rebase HEAD~1 --onto origin/4
```

Assuming that you're checked out on the PR branch and "origin" in this case is a remote with an up to date copy of `4 (preferably origin is just this repo). You might have to solve conflicts with the rebase.

Additionally, the tests are failing as you need to ensure you commit the dist files for the JavaScript. Just a `yarn build` and commit whatever is changed.

I don't have time to check this out and play around sorry, I'll leave that to one of the SSLtd team.

**Comment by brynwhyman** [comment]
Awesome! There's actually an open issue for this requirement that includes some light requirements from the Silverstripe UX team (I've just asked them to make the design link public).

https://github.com/dnadesign/silverstripe-elemental/issues/562

**Comment by JoshuaCarter** [comment]
Hey @ScopeyNZ and @brynwhyman, a few points/questions:

1. I've moved the 'Duplicate' option before 'Archive'.
2. Code now adds ' copy {optional number starting with 2}' rather than multiples of ' (Copy)'.
3. I'm doing this for a client (on their dime) and they're using 4.0.5 which is why I've targeted the `4.0` branch. So I can't necessarily justify the additional work to make this work on the `4` branch (including animation/alert which aren't on `4.0`).
4. Would the work done on `4` normally be back-ported to `4.0`? Given that each branch needs a different implementation (from my very quick look anyway), I'm guessing not.
5. Any chance of this being merged into `4.0` for a 4.6 release, and then cherry-picked to `4` (and fixed/improvements made) by someone on your end? We may need to stick to a fork for now if not.

Cheers.

**Comment by ScopeyNZ** [comment]
> 4. Would the work done on `4` normally be back-ported to `4.0`? Given that each branch needs a different implementation (from my very quick look anyway), I'm guessing not.

Not unless it's a bugfix

> 5. Any chance of this being merged into `4.0` for a 4.6 release, and then cherry-picked to `4` (and fixed/improvements made) by someone on your end? We may need to stick to a fork for now if not.

Unfortunately, we can't put features like this in bugfix releases (`4.0.next`) as that would be breaking our semantic versioning commitments. You will have to stay on a fork, or use some form of `composer-patches` 

I hope that doesn't discourage contributing back though, because once it's merged then we have to maintain it for you 😅

**Comment by JoshuaCarter** [comment]
@ScopeyNZ Thanks for the info. We'll stick to a fork for now and aim to re-target this to `4` in the near future with an eye to upgrading the module on our end, etc.

Cheers.

**Comment by JoshuaCarter** [comment]
@ScopeyNZ Have re-targeted this PR to `4` and tested locally. Don't think that triggers the CI tests on here so might want to manually redo those.

**Comment by ScopeyNZ** [comment]
As long as you switch the base branch first, it should run the suite when you force-push.

**Comment by JoshuaCarter** [comment]
@ScopeyNZ You can see in the timeline that I switched branches and did a force push but that didn't seem to trigger the tests.

**Comment by ScopeyNZ** [comment]
image
Looks like they did to me.

**Comment by ScopeyNZ** [comment]
Although it looks like the commit reference is different 🤔 . The branch and time match up though.

**Comment by JoshuaCarter** [comment]
Huh... I see:
image
Nvm I guess lol.

**Comment by JoshuaCarter** [comment]
@ScopeyNZ force pushed the top commit (no changes) to trigger. Displayed properly for me this time, so good to go afaik!

**Comment by ScopeyNZ** [comment]
Sure. I don't have a capability/bandwidth to give this a once over right now - so I'll see if I can call some favours with the SSLtd. team this week.

**Comment by JoshuaCarter** [comment]
Many thanks!

**Comment by JoshuaCarter** [comment]
Hey @ScopeyNZ Just checking for movement here. Cheers.

**Comment by ScopeyNZ** [comment]
Oh, I've lost my merge ability. Lol.

**Comment by sachajudd** [comment]
I've just chatted with the team at Silverstripe Ltd and it looks like they'll prioritise this issue in the next month or so unless a core contributor or someone part of this module gets to it first 🙂

**Note for the team:** It would be great if someone could test how this works with versioned-snapshots and check to see when duplicating a block if it adds a new block in History.

**Comment by tractorcow** [comment]
I just noticed that blocks with `private static $inline_editable = false;` don't have a duplicate menu. We can add this in via the gridfield actions right?

**Comment by srehman130** [comment]
>I just noticed that blocks with private static $inline_editable = false; don't have a duplicate menu. We can add this in via the gridfield actions right?

We are having similar issues. Has anyone been able to look into this?

**Pull request merged**
