### PR TITLE
NEW: Compatibility with GraphQL 4 changes

### PR DESCRIPTION
**Pull request by unclecheese**
## Summary

Use new context provider API. No more BuildState.

Depends on https://github.com/silverstripe/silverstripe-graphql/pull/352

### CODE REVIEW

**Comment by unclecheese** [comment]
Confirmed failures are due to missing `UserContextProvider` class.

**Comment by tractorcow** [comment]
This change just broke compatibility with graphql 3. Do you want to fix the composer dependencies to reflect that 3 is no longer supported?

**Comment by unclecheese** [comment]
Shouldn't have. We test everything in both v3 and v4. https://travis-ci.com/github/silverstripe/silverstripe-elemental/jobs/519607824

What issue are you seeing?

**Comment by tractorcow** [comment]
my typeMap is no longer respected due to the removal of 
`return StaticSchema::inst()->typeNameForDataObject(static::class);`

**Comment by tractorcow** [comment]
I guess my attempt to upgrade a framework 4.7 to 4.8 can't be done unless I upgrade to graphql 4 huh. Oh well.

**Comment by unclecheese** [comment]
We are supporting both versions simultaneously. The method you're referring to still exists in GraphQL 3, right? Can't you just run GraphQL 3?

**Comment by tractorcow** [comment]
Yes, the method exists, and elemental no longer calls it.

So with graphql config as below:

```yaml
      typeNames:
        myProject\HeroBlock: HeroBlock
```


I still get graphql results as below:

```json
"node": {
      "ID": "6",
      "BlockSchema": {
        "typeName": "myProject_HeroBlock",
        "title": "About the collection / Mō te kohinga",
        "showTitle": 1
  }
}
```

when it should be

```json
"node": {
      "ID": "6",
      "BlockSchema": {
        "typeName": "HeroBlock",
        "title": "About the collection / Mō te kohinga",
        "showTitle": 1
  }
}
```

**Comment by unclecheese** [comment]
Right, OK.. The "backward compatibility" is focussed on the CMS, so there may still be upgrade issues in your frontend app. I think this is really as simple as adding a fork in the typeName function that uses the old GraphQL 3 method if it exists, right? Can we fix this in two lines of code?

**Comment by unclecheese** [comment]
```php
    public static function getGraphQLTypeName(): string
    {
        return class_exists(StaticSchema::class)
            ? StaticSchema::inst()->typeNameForDataObject(static::class)
            : str_replace('\\', '_', static::class);
    }
```

**Comment by tractorcow** [comment]
That'd probbably do it!

Sorry, i've been out of the silverstripe space for a while, not sure what the state of play is with the recent versions. :)

**Comment by tractorcow** [comment]
Thanks for the quick response too. I don't need a fix urgently, I just wanted to report back my findings in case it was useful for you. I'm happy to keep my site on 4.7 in the mean time.

**Comment by tractorcow** [comment]
convention over configuration is the way to go by the way. graphql 4 is very cool.

**Comment by unclecheese** [comment]
Thanks! If you like convention over configuration, you'll love what we're doing with NextJS. :-)

**Comment by unclecheese** [comment]
Can you just apply that patch locally and let me know if it works, and if so, I'll just make a PR now.

**Comment by tractorcow** [comment]
Will do, 1 moment.

**Comment by tractorcow** [comment]
looks good 👍 

```json
"node": {
                "ID": "6",
                "BlockSchema": {
                  "typeName": "HeroBlock",

```

**Comment by tractorcow** [comment]
When I get some time, I'll just upgrade to graphql 4 (that's the real fix here, I have to admit).

**Comment by unclecheese** [comment]
PR is up https://github.com/silverstripe/silverstripe-elemental/pull/912

**Pull request merged**
