### PR TITLE
ENH Skip validation when creating a new elemental block

### PR DESCRIPTION
**Pull request by GuySartorelli**
Requires https://github.com/silverstripe/silverstripe-framework/pull/11202 for CI to go green
## Issues
- https://github.com/silverstripe/silverstripe-elemental/issues/1149

### CODE REVIEW

**Comment by michalkleiner** [comment]
I know this targets `6` but should `composer.json` also be updated to explicitly require `silverstripe/framework: ^6`? Or is that implied from the module version and they are in tied together through major versions?

**Comment by GuySartorelli** [comment]
The constraint for the `6` branch of this module already requires framework `^6`: https://github.com/silverstripe/silverstripe-elemental/blob/1512b1755b6186bec40ff99fc0c4921abbdd8f75/composer.json#L22

**Review by emteknetnz — APPROVED** [review]
I've merged the dependent framework PR and am rerunning CI. Merge on green.

**Comment by GuySartorelli** [comment]
I had missed some things, fixed now.

**Comment by GuySartorelli** [comment]
Not sure why CI isn't running against this... I tried force pushing again and it didn't trigger it. Will wait a bit and see if GitHub is just congested.

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
